[tool.poetry]
name = "sierpinski-figures"
version = "0.1.0"
description = ""
authors = ["Kacper <74537153+KasmyrA@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
